Cocopods setup with demo project added.
SimformSolutionsPvtLtd/SSVerticalPanoramaImage pull request #2
Opened 2023-07-02 18:28 UTC by purvesh-d

2023-07-03 05:05 UTC, iOSDev-Auction commented on SSVerticalPanoramaImage/Classes/OpenCVClass/CVWrapper.mm
> +        NSLog (@"result... %@", result);
Coding Standaard - Print statement

2023-08-23 04:21 UTC, bhargavbajani-simformsolutions requested changes

2023-08-23 04:21 UTC, bhargavbajani-simformsolutions commented on SSVerticalPanoramaImage.podspec
> +  s.summary          = 'A short description of SSVerticalPanoramaImage.'
missing description

2023-08-23 04:21 UTC, bhargavbajani-simformsolutions commented on SSVerticalPanoramaImage.podspec
> +                          TODO: Add long description of the pod here.
Missing description

2023-08-23 04:21 UTC, bhargavbajani-simformsolutions commented on SSVerticalPanoramaImage/Classes/SSVerticalPanorama.swift
> +                    let bundle = Bundle(for: Self.self)
weak self missing

2023-08-23 08:33 UTC, bhargavbajani-simformsolutions commented on SSVerticalPanoramaImage.podspec
> +  s.description      = <<-DESC
The description title and end  "DESC" should be removed.

2023-08-23 12:43 UTC, purvesh-d commented on SSVerticalPanoramaImage.podspec
> +  s.description      = <<-DESC
As I can see in pod official doc syntax mention at [here](https://guides.cocoapods.org/syntax/podspec.html#description),  This "<<-DESC ..... DESC" is the syntax and we have to write our content inside it. 


Also I have explored some well-known pod listed below and they are also doing the same. 

Firebase: https://github.com/firebase/firebase-ios-sdk/blob/master/Firebase.podspec
Kingfisher: https://github.com/onevcat/Kingfisher/blob/master/Kingfisher.podspec
Pod Official Doc: https://guides.cocoapods.org/syntax/podspec.html#description

2023-08-23 12:46 UTC, bhargavbajani-simformsolutions approved these changes

2023-08-23 12:47 UTC, merged